Solen Ant Hole Add-On
UOX3DevTeam/UOX3 pull request #158
Opened 2022-12-11 04:56 UTC by DragonSlayer62

Solen Hives and Ants was introduced in LBR during a event called When Ants Attack.

We have the Randomly spawning black holes that can be put out with event tags for events.
Description how it works
1. When walked on it will spawn 2 to 5 ants
2. Keeps track of the deaths of each ant so it cant over spawn the area.
3. Has a 5 min cool down so it can't keep spawning when walking over.
4. Double click on the hole and it will take you to the solen hive.

We also have the Main Solen hive Entrances.
Description how it works
1. You double click it will take you down to the solen hive depending on what location you are using.
2. Double click in the middle of the black inside the solen hive it will return you to the surface.

World Decorations that come with this file will place the Main Entrances and Exits around the World for Felucca Map only.

2025-10-16 20:53 UTC, strattond requested changes
More questions than critiques

2025-10-16 20:53 UTC, strattond commented on data/dfndata/house/house.dfn
> +[HOUSE ITEM 600]
Is there a particular reason why the dirt ones are ever so slightly different in position?

2025-10-16 20:53 UTC, strattond commented on data/dfndata/items/houseaddons/solenanthole.dfn
> +[dirt1]
Worth a [basedirt] that has a name, weigh, movable and decay commonality?

2025-10-16 20:53 UTC, strattond commented on data/dfndata/items/houseaddons/solenanthole.dfn
> +[shentrancepeice1]
Ditto for a [base_shentrancepiece] - also, you've spelt piece wrong :)

2025-10-16 20:53 UTC, strattond commented on data/dfndata/npc/hymenoptera_base.dfn
> +GETUO=ambitious_black_solen_queen_lbr
So the implication is that this LBR+ based on the name.

Should there be a GETUO, GETT2A, GETUOR or GETTD if they're prior?  What happens if they're missing?

2025-10-16 20:53 UTC, strattond commented on data/dfndata/npc/npc_aos/hymenoptera_aos.dfn
> +//Bracelet of Binding needs created
So ... where is it?  Either of these PACKITEMs don't seem a match?

2025-10-16 20:53 UTC, strattond commented on data/js/server/teleporter/teleporter_solen_hive.js
> +	"5657,1898": [5750, 1894],
So this is "C leads to center area", but 2 above with the same target coordinates is "B leads to level 2"

Are "center area" and "level 2" the same?

2025-10-16 20:53 UTC, strattond commented on data/js/server/teleporter/teleporter_solen_hive.js
> +var entranceMap = {
Wondering if it's worth pulling targets out as meaningfully named constants and using those constants in the key value?
e.g. with the Solen Hive teleporters, there's lots that go to the same spot.

```
var SOLEN_LEVEL_2 = [5725, 1894];
...
"5757,1794": SOLEN_LEVEL_2,
```

2025-10-17 08:23 UTC, Xoduz requested changes

2025-10-17 08:23 UTC, Xoduz commented on data/dfndata/spawn/trammel/spawn_trammel_dungeon_solen_hives.dfn
> +WORLD=0
World number is incorrect on these spawn regions. By the name of the file they look intended for trammel?

2025-10-17 08:23 UTC, Xoduz commented on data/dfndata/npc/hymenoptera_base.dfn
> +GETUO=ambitious_black_solen_queen_lbr
Originally for LBR+, but no reason why people shouldn't be able to enable it for earlier eras if desired. But the way the system is currently setup, it does require that tag for each era, or a broken NPC will spawn instead.

2025-10-17 17:09 UTC, DragonSlayer62 commented on data/dfndata/house/house.dfn
> +[HOUSE ITEM 600]
Yes they make a tunnel

<img width="327" height="290" alt="image" src="https://github.com/user-attachments/assets/d2061c31-047c-47e5-962a-31fb5700cbbd" />

<img width="235" height="193" alt="image" src="https://github.com/user-attachments/assets/3091fb98-63cf-4a11-aca7-31c5bc0f1fe7" />

2025-10-17 17:10 UTC, DragonSlayer62 commented on data/dfndata/items/houseaddons/solenanthole.dfn
> +[dirt1]
<img width="235" height="193" alt="image" src="https://github.com/user-attachments/assets/2ef2a8cd-2863-4d1b-a4fc-79849ef8a33d" />
<img width="210" height="219" alt="image" src="https://github.com/user-attachments/assets/2a8e2651-0ef0-4b7e-87a7-61e3b5e1d34a" />


this creates the tunnels two differant versions

2025-10-17 17:11 UTC, DragonSlayer62 commented on data/dfndata/items/houseaddons/solenanthole.dfn
> +[shentrancepeice1]
will fix thanks

2025-10-17 17:14 UTC, DragonSlayer62 commented on data/dfndata/npc/npc_aos/hymenoptera_aos.dfn
> +//Bracelet of Binding needs created
this not scripted yet comment for when it does get added

2025-10-17 17:15 UTC, DragonSlayer62 commented on data/js/server/teleporter/teleporter_solen_hive.js
> +	"5657,1898": [5750, 1894],
https://[uo.stratics.com/content/atlas/solenhive.php](https://uo.stratics.com/content/atlas/solenhive.php) so the dungeon is just really one level but broken into 4 sections that have different teleport points.

2025-10-17 17:16 UTC, DragonSlayer62 commented on data/js/server/teleporter/teleporter_solen_hive.js
> +var entranceMap = {
well, they go to the same area just different parts of that area

2025-10-17 17:16 UTC, DragonSlayer62 commented on data/dfndata/spawn/trammel/spawn_trammel_dungeon_solen_hives.dfn
> +WORLD=0
Fixed

2025-10-19 20:07 UTC, strattond commented on data/dfndata/items/houseaddons/solenanthole.dfn
> +[dirt1]
Yeah, my point was more that for dirt1 -> dirt9, the NAME, weight, movable and decay values are all the same.  It's only ID and possibly COLOUR that changes.

You could move the NAME, weight, movable and decay into a common basedirt and call it a day?

In fact, looking at solenentrancehole and it's variants, the weight, movable and decay values match there too.

So you could have a "base_immovable" that is the weight, movable and decay and GET those where appropriate.  For example:

```
[base_immovable]
{
weight=100
movable=2
decay=0
}

[ahole]
{
NAME=a hole
ID=0x122A
COLOUR=0x1
GET=base_immovable
SCRIPT=2752
]
```

2025-10-19 23:18 UTC, DragonSlayer62 commented on data/dfndata/items/houseaddons/solenanthole.dfn
> +[dirt1]
I see what you mean I fixed it.

2025-10-21 22:22 UTC, strattond approved these changes

2025-10-23 10:19 UTC, Xoduz requested changes

2025-10-23 10:19 UTC, Xoduz commented on data/dfndata/items/houseaddons/solenanthole.dfn
If these items are intended specifically for the solen ant holes, rename them. Either add the dirt items as generic items in a more generic file, or rename them to be specifically for the solen ant holes. Example: [base_anthole_dirt], [anthole_dirt1], [anthole_dirt2], {anthole], etc.

2025-10-23 10:19 UTC, Xoduz commented on data/dfndata/npc/npc_aos/hymenoptera_aos.dfn
> +//Bracelet of Binding needs created
I think you can comment out loot like this until the item functionality as been scripted. Don't add "junk items" that do nothing, can't be sold for money, just take up space, etc.

2025-10-23 10:19 UTC, Xoduz commented on data/dfndata/spawn/felucca/spawn_felucca_dungeon_solen_hives.dfn
> +[REGIONSPAWN 4300]
No. This is lazy design, and risks setting up situations where too many NPCs spawn in a single place, since it's all random across the entire dungeon. Split this up into additional spawn regions, 6 of them, each with MAXNPC=16 or some such. Same for Trammel spawns. Something like this:

<img width="807" height="610" alt="image" src="https://github.com/user-attachments/assets/14ff44fe-63c2-4ee6-b37d-9a2a2bc3d58a" />

2025-10-23 10:19 UTC, Xoduz commented on data/js/jsdata/worldtemplates/felucca_solenhive.jsdata
This is good stuff, but... it's not hooked up to anything, so these items will never spawn unless someone does 'decorate load felucca_solenhive

Ideally, this would be part of the admin welcome gump, as an option for additional decorations for Felucca/Trammel:

<img width="781" height="432" alt="image" src="https://github.com/user-attachments/assets/77698475-3ea6-4a97-97f4-3ce015e0229a" />


Also, the template file includes several "deed" items (id 5360), which spawn very visible in the world? I suggest removing these from the file.

2025-10-23 10:19 UTC, Xoduz commented on data/js/server/teleporter/teleporter_solen_hive.js
> +			return true;
"return true" here causes a system message that says "You can't think of a way to use that item." because it tries to pass the double-click event to code, and finds nothing actionable. Change to return false (as well as for the next one below.)

2025-10-23 10:19 UTC, Xoduz commented on data/js/server/teleporter/teleporter_solen_hive.js
> +*	We have the Randomly spawning black holes that can be put out with event tags for events.
Are these ant holes randomly spawned? Should there be spawn logic that makes this happen? Are they currently just fixed ant holes in every single possible location?

2025-10-23 21:56 UTC, DragonSlayer62 commented on data/dfndata/items/houseaddons/solenanthole.dfn
Ill rename them because there tied to a script

2025-10-24 01:08 UTC, DragonSlayer62 commented on data/js/server/teleporter/teleporter_solen_hive.js
> +*	We have the Randomly spawning black holes that can be put out with event tags for events.
the ones in decoration file are fixed the random ones is the ones a gm can use to put out for players to use and those will randomly drop you someone in the dungeon.

2025-10-27 12:35 UTC, Xoduz approved these changes

2025-10-27 12:35 UTC, merged