AOS Properties Regeneration
UOX3DevTeam/UOX3 pull request #277
Opened 2024-04-30 18:48 UTC by DragonSlayer62

Regeneration Hit Points
Regeneration Stam Points
Regeneration Mana Points

Added AOS formula for mana regeneration. Only Active in AOS and up.

2025-01-14 01:41 UTC, strattond requested changes
Smal requested improvements

2025-01-14 01:41 UTC, strattond commented on source/cServerData.cpp
> +			HealthRegenCap( std::stof( value ));
stof returns a floating point value - but the caps take a SI16.

I'd expect this to be different e.g. stoi

2025-01-14 01:41 UTC, strattond commented on source/cServerData.cpp
> +			HealthRegenCap( std::stof( value ));
```suggestion
			HealthRegenCap( std::stoi( value ));
```

2025-01-14 01:41 UTC, strattond commented on source/cServerData.cpp
> +			StaminaRegenCap( std::stof( value ));
```suggestion
			StaminaRegenCap( std::stoi( value ));
```

2025-01-14 01:41 UTC, strattond commented on source/cServerData.cpp
> +			ManaRegenCap( std::stof( value ));
```suggestion
			ManaRegenCap( std::stoi( value ));
```

2025-01-14 20:54 UTC, DragonSlayer62 commented on source/cServerData.cpp
> +			HealthRegenCap( std::stof( value ));
xuri has pulled this so not sure what updates he made or changes ill wait to see

2025-04-21 20:24 UTC, Xoduz approved these changes
DS said it looked ok :P

2025-04-21 20:28 UTC, merged