Lower Requirements Propertie
UOX3DevTeam/UOX3 pull request #278
Opened 2024-05-01 04:29 UTC by DragonSlayer62

Added AOS Lower Requirement propertie.

2024-10-06 16:05 UTC, DragonSlayer62 commented
After testing this again by itself, seems to be working from the standpoint of AOS. from aos launch

2025-01-24 18:38 UTC, Xoduz requested changes
UOGuide mentions that the "Lower Requirement" property also lowers the actual weight of the item:
> It lowers the overall weight of an item by the percentage given.

Might want to work that into CBaseObject::GetWeight(), so the weight returned is reduced by the percentage given in the lower requirement property. That will reduce the effective weight of the weapon, but won't touch the original weight of it.

ALSO, I don't see anywhere reading in the LOWERTATREQ tag from DFNs, only for reading it in from worldfiles.

Lastly, something to consider: It's not just Strength that can be a requirement for equipping items in UOX3. Intelligence and Dexterity properties on items will also determine whether they can be equipped by a player. Should we not support these as well, when we're adding a new property that can lower the requirement of one particular stat (Strength)?

2025-01-25 00:24 UTC, DragonSlayer62 commented
Per osi it only allows STR i was going off old uo.stratics page from way back machine. for aos

2025-01-25 18:02 UTC, Xoduz approved these changes

2025-01-25 18:02 UTC, merged