Spawner Gump
UOX3DevTeam/UOX3 pull request #279
Opened 2024-05-05 18:37 UTC by DragonSlayer62

This gives spawners a gump to edit them, You do not have to use it but very nice if your not wanting to mess with a lot of set commands.

2024-10-06 16:12 UTC, DragonSlayer62 commented
This has been very helping for the spawners I have placed around my shard without having to remember some commands so this might be ready, but you might want to make some tweaks.

2025-01-24 18:21 UTC, Xoduz requested changes

2025-01-24 18:21 UTC, Xoduz commented on data/js/server/misc/spawnergump.js
> +	var socket = pUser.socket;
Add in check here to ensure only GMs can trigger the spawner gump. There might be cases where shards might want a spawner object to be visible to players - example could be a destructible item that will spew out monsters until it is destroyed - and you don't want players to be able to double-click it to edit the spawn properties :)

2025-01-25 00:22 UTC, DragonSlayer62 commented on data/js/server/misc/spawnergump.js
> +	var socket = pUser.socket;
Add isGM check.

2025-01-25 07:15 UTC, Xoduz requested changes

2025-01-25 07:15 UTC, Xoduz commented on data/js/server/misc/spawnergump.js
>  	socket.tempObj = iUsed;
Shift socket.tempObj = iUsed to inside the if condition, so it only gets set if the conditions are met :)

2025-01-25 14:02 UTC, DragonSlayer62 commented on data/js/server/misc/spawnergump.js
>  	socket.tempObj = iUsed;
okay

2025-01-25 14:05 UTC, DragonSlayer62 commented on data/js/server/misc/spawnergump.js
>  	socket.tempObj = iUsed;
Fixed

2025-01-25 14:58 UTC, Xoduz approved these changes

2025-01-25 14:58 UTC, merged