Added ArtifactRarity AOS Property
UOX3DevTeam/UOX3 pull request #280
Opened 2024-05-10 01:23 UTC by DragonSlayer62

ARTIFACTRARITY=#
Artifact Rarity is an item property that is visible on some artifacts and meant to give players an idea of how rare the item is. Items with rarity 1 are supposed to be common while rarity 12 are extremely scarce.

2024-10-06 16:13 UTC, DragonSlayer62 commented
This works well it's just a new tag to display the artifact status of items it was no longer used after ML. but if your wanting an AOS type shard like most people want this will be something they will want to use. I use it for value on items for players so they can say oh this rare or not rare.

2025-01-14 03:59 UTC, strattond commented
The artifact rarity has been added to the *base* object - not to items.

I think it would make sense to attach it to CItem rather than cBaseObject - unless somehow characters can be rare?

2025-01-14 22:12 UTC, DragonSlayer62 commented
Fixed the artifact tag

2025-01-16 03:09 UTC, strattond requested changes

2025-01-16 03:09 UTC, strattond commented on source/cItem.cpp
> +	if( CanBeObjType( OT_ITEM ))
As with the other PR, because we're already in CItem, this should be reducable to just `UpdateRegion();`

We're in Item, so can always be item, and shouldn't need to static cast.

2025-01-16 03:40 UTC, DragonSlayer62 commented
fixed

2025-01-16 04:04 UTC, strattond approved these changes
Pending testing satisfaction, this looks OK to me

2025-01-17 02:21 UTC, merged