Added Durability Bonus Prop
UOX3DevTeam/UOX3 pull request #281
Opened 2024-05-12 01:30 UTC by DragonSlayer62

2024-10-06 16:10 UTC, DragonSlayer62 commented
This is ready to go

2025-01-14 04:01 UTC, strattond commented
Like the artifact rarity (https://github.com/UOX3DevTeam/UOX3/pull/280), this exposes the stuff to JS via Item, but it is added to the Base Object - this makes more sense to hang off cItem instead, as it doesn't have a conceptual value for a character

2025-01-16 03:07 UTC, strattond requested changes

2025-01-16 03:07 UTC, strattond commented on source/cItem.cpp
> +	if (CanBeObjType(OT_ITEM))
Given this only applies to Items (i.e. CanBeObjType(OT_ITEM) is always true), you can probably remove the IF directly and just call UpdateRegion().

You also shouldn't need to do a static cast, as you're already in CItem at this point.

So this whole if could be reduced to, hopefully, `UpdateRegion();`

2025-01-16 03:36 UTC, DragonSlayer62 commented on source/cItem.cpp
> +	if (CanBeObjType(OT_ITEM))
okay will update

2025-01-16 04:05 UTC, strattond approved these changes
Pending testing, this looks OK to me

2025-01-17 04:18 UTC, closed without merging