New Shield Type 107
UOX3DevTeam/UOX3 pull request #283
Opened 2024-05-14 00:20 UTC by DragonSlayer62

Added New Shield Type 107

2025-01-14 06:17 UTC, strattond reviewed
So in theory - looking at the code, I *think* we support the concept of a nested GET.

Would it be worth introducting a `[base_shield]` that inherits from `base_item` and applies type 107, then change the existing shields to get from `base_shield` instead?

It may give you other opportunities for commonising other attributes too (e.g. layer=0x02, decay, etc)

2025-01-15 00:21 UTC, DragonSlayer62 commented
Okay so I was good at making a type but not sure what you mean with that. sorry still learning the code base

2025-01-15 02:55 UTC, strattond commented
> Okay so I was good at making a type but not sure what you mean with that. sorry still learning the code base

So you've updated the dfns to look like this for each shield:

```
[base_bronze_shield]
{
get=base_item
name=bronze shield
id=0x1b72
type=107
decay=1
good=16
layer=0x02
restock=10
str=20
}
```

type=107 and a few other things are all common.  My suggestion would be to change it to something like:

```
[base_shield]
{
get=base_item
type=107
decay=1
good=16
layer=0x02
restock=10
str=20
}

[base_bronze_shield]
{
get=base_shield
name=bronze shield
id=0x1b72
}
```

That way, anything common to a shield is in the `base_shield` section, and each one is just specialised.

I *think* this will work.

2025-01-15 05:32 UTC, DragonSlayer62 commented
oh, okay I see what you're saying yeah that would work.

2025-01-16 23:44 UTC, DragonSlayer62 commented
Okay updated

2025-01-17 00:01 UTC, strattond requested changes

2025-01-17 00:01 UTC, strattond commented on data/dfndata/items/gear/armor/base_armor.dfn
>  str=20
This wasn't present on previous definitions - are we sure we want this?

2025-01-17 00:01 UTC, strattond commented on data/dfndata/items/gear/armor/base_armor.dfn
> -dyeable=1
Dyeable was not moved to the base

2025-01-17 00:01 UTC, strattond commented on data/dfndata/items/gear/armor/base_armor.dfn
> -movable=1
Movable was not moved to the base

2025-01-17 00:01 UTC, strattond commented on data/dfndata/items/gear/armor/base_armor.dfn
> -movable=1
Movable was not moved to the base

2025-01-17 00:08 UTC, DragonSlayer62 commented on data/dfndata/items/gear/armor/base_armor.dfn
> -dyeable=1
you cant dye shields i wander if that was a messup

2025-01-17 00:09 UTC, DragonSlayer62 commented on data/dfndata/items/gear/armor/base_armor.dfn
>  str=20
type 107 is the shield that lets code know what it is.

2025-01-17 00:15 UTC, strattond commented on data/dfndata/items/gear/armor/base_armor.dfn
>  str=20
No, I mean specifically `str=20`

2025-01-17 01:40 UTC, strattond approved these changes

2025-01-17 02:28 UTC, merged