Buff Bar System
UOX3DevTeam/UOX3 pull request #284
Opened 2024-05-20 14:30 UTC by DragonSlayer62

Buffs are positive effects on your character, shown as a green icon.

Debuffs are a negative effect on your character shown as a red icon.

https://uo.com/wiki/ultima-online-wiki/technical/buff-and-debuff-icons/

I only added Healing using buff bar at the moment.

2024-10-06 16:06 UTC, DragonSlayer62 commented
This currently works halfway because a lot of things like spells and stuff are in the core so i say we can put this on back burner or it can be added with just the few ones that its working with.

2025-01-14 06:26 UTC, strattond requested changes

2025-01-14 06:26 UTC, strattond commented on data/js/server/global.js
> +	if( disguiseKitTime != 0 )
I'm concerned with this being `!= 0` - I'd wonder if it should be `> 0` instead, because that implies `disguiseKitTime` is still in the future.

This will also trigger if somehow `disguiseKitTime` is in the past and the timers got backed up.

2025-01-14 06:26 UTC, strattond commented on data/js/skill/healing.js
> +				buffIcon = 1069;
I wouldn't be unhappy to know where/how you're finding these magic numbers from.

2025-01-15 00:13 UTC, DragonSlayer62 commented on data/js/server/global.js
> +	if( disguiseKitTime != 0 )
I  see what your talking about

2025-01-15 02:51 UTC, strattond approved these changes
These changes look OK to me, from what I can see.  Just need a quick test before merging to make sure it still works after code change @DragonSlayer62

2025-01-17 02:16 UTC, DragonSlayer62 commented
did one and seems to work way post to be now thats nice.

2025-01-17 02:21 UTC, merged

2025-12-17 08:24 UTC, Xoduz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Buff Bar](https://trello.com/c/9On4umAE/257-buff-bar)