Special Moves
UOX3DevTeam/UOX3 pull request #285
Opened 2024-05-26 00:06 UTC by DragonSlayer62

This is the 12 AOS abilites that are in the book on the paperdoll.

2024-10-06 16:07 UTC, DragonSlayer62 commented
This is complete AOS ready for uox3 It has been on my shard and tested by the players since I built it. This was based on AOS launch.

2025-01-24 18:16 UTC, Xoduz requested changes

2025-01-24 18:16 UTC, Xoduz commented on data/js/combat/special_moves.js
> +		28: { manaAmount: 35 },		// Serpent Arrow
This seems to cover more abilities than the original PR description mentioned. Are they all implemented? If not, can comment out the ones that are not covered by this PR?

2025-01-24 18:16 UTC, Xoduz commented on data/js/combat/special_moves.js
Please do a pass on this script to convert spaces to tabs and ensure stuff lines up properly :)

2025-01-24 18:16 UTC, Xoduz commented on data/js/server/global.js
> +
Add a new setting in UOX.INI: ENABLESPECIALMOVES=#
Make it a bitset style setting, where 0x1 enables LBR special moves, 0x2 enables AOS ones, 0x4 SE ones, 0x8 ML ones and 0x10 SA ones.

Then add a check here to see if the setting is higher than 0 before attaching the script.

2025-01-24 18:16 UTC, Xoduz commented on data/js/server/global.js
> +	}
See above comment about adding uox.ini setting and checking for it here before attaching script to player.

2025-01-24 18:16 UTC, Xoduz commented on data/js/combat/special_moves.js
> +function onSpecialMove( pUser, abilityID )
I don't see anywhere in the PR that references or calls upon onSpecialMove. What am I missing? How does it get called?

2025-01-25 00:41 UTC, DragonSlayer62 commented on data/js/server/global.js
> +
There was no special moves book in LBR just AOS and up.

2025-01-25 00:46 UTC, DragonSlayer62 commented on data/js/combat/special_moves.js
> +		28: { manaAmount: 35 },		// Serpent Arrow
I added all thge abilties for future expansions reason for the restrictedAbilities

2025-01-25 00:47 UTC, DragonSlayer62 commented on data/js/combat/special_moves.js
> +function onSpecialMove( pUser, abilityID )
that is the script being attached to the char the packet is calling this when you click the book something like quest button.

2025-01-25 07:17 UTC, Xoduz commented on data/js/combat/special_moves.js
> +function onSpecialMove( pUser, abilityID )
Oops, that's true :) Thanks

2025-01-25 07:20 UTC, Xoduz commented on data/js/server/global.js
> +
You're right, I was thinking of the original crushing blow/paralyzing blow/concussion blow from UOR, but we already added support for those previously. We should still do the setting for AOS/SE/ML/SA special moves though :)

2025-01-26 18:37 UTC, Xoduz approved these changes

2025-01-26 19:16 UTC, merged