Small Fixes to Get Command
UOX3DevTeam/UOX3 pull request #289
Opened 2024-06-12 04:32 UTC by DragonSlayer62

Fixed items handling correct target for resists
Added Getting the resists on chars

2024-10-06 16:09 UTC, DragonSlayer62 commented
ready to go.

2025-01-24 17:00 UTC, Xoduz requested changes
Just needs a changelog entry

2025-01-25 00:50 UTC, DragonSlayer62 commented
Added changelog

2025-01-25 07:26 UTC, Xoduz approved these changes

2025-01-25 07:29 UTC, merged