Swing Speed Increase
UOX3DevTeam/UOX3 pull request #291
Opened 2024-06-16 06:37 UTC by DragonSlayer62

2025-01-24 17:30 UTC, Xoduz requested changes

2025-01-24 17:30 UTC, Xoduz commented on source/cServerData.cpp
Make sure to set a default value for SwingSpeedIncreaseCap() setting via CServerData::ResetDefaults(). Can also mention the default value in changelog entry.

2025-01-24 17:30 UTC, Xoduz commented on source/combat.cpp
The changes in CHandleCombat::GetCombatTimeout() to calculate swing delay based on era won't work as intended, because the weapons in the different era-specific DFNs has the swingspeed formulas of each specific era baked into the SPD values (determined via a spreadsheet!). This allows applying era-appropriate swing speeds to weapons from _future_ eras in _older_ eras while keeping the balance between weapons relatively intact, so someone can do an LBR-focused shard but allow weapons from future eras without upsetting the balance.

Please change this to just insert the swingspeed bonus increase into the default formula, i.e.
`getDelay = baseValue / ( getDelay * getOffset * speedFactor ) / globalAttackSpeed;`

2025-01-24 17:30 UTC, Xoduz commented on source/Changelog.txt
> +	Added new DFN tags for Items:
This seems to be supported for both Items _and_ Characters?

2025-01-25 00:51 UTC, DragonSlayer62 commented on source/cServerData.cpp
it is already set at 60 for when ini loads.

2025-01-25 00:54 UTC, DragonSlayer62 commented on source/combat.cpp
like this

getDelay = baseValue / ( getDelay * getOffset * speedBonus ) / globalAttackSpeed;

2025-01-25 00:54 UTC, DragonSlayer62 commented on source/Changelog.txt
> +	Added new DFN tags for Items:
yes ill update that

2025-01-25 00:56 UTC, DragonSlayer62 commented
fixed

2025-01-25 07:36 UTC, Xoduz commented on source/combat.cpp
Keep this:
`SI32 baseValue = 15000;`
and this one for fleeing targets:
`baseValue = 10000; `

Keep the speedfactor stuff, but replace the if/else stuff at the bottom with just that one line:
`getDelay = baseValue / ( getDelay * getOffset * speedFactor ) / globalAttackSpeed;`

2025-01-25 07:38 UTC, Xoduz commented on source/cServerData.cpp
I don't see that in this PR? There's usually a line per setting in cServerData that sets the default, but that doesn't seem to be present for the swingspeedincreasecap.

2025-01-25 15:26 UTC, Xoduz commented on source/combat.cpp
I have mashed potato for brains. Ignore this.

2025-01-25 15:34 UTC, Xoduz approved these changes

2025-01-25 16:08 UTC, merged