Requried Free Hand
UOX3DevTeam/UOX3 pull request #294
Opened 2024-07-07 19:21 UTC by DragonSlayer62

Added Requirement to drink potion hand has to be free, This can be disabled within the potion.js file by switching the reqfreehand to false.

2025-01-24 16:55 UTC, Xoduz requested changes

2025-01-24 16:55 UTC, Xoduz commented on source/Changelog.txt
> +	Added Required Free Hand (js potion).
Elaborate. You wrote it so nicely in the PR description, do the same for changelog entries! :) These are the entries that are used to list out changes with releases, so people can scroll through and see what fixed/additions/changes were made. "Added Required Free Hand" doesn't say a lot, but your PR description does (just update "reqfreehand" to match the variable name in the script)

> Added Requirement to drink potion hand has to be free, This can be disabled within the potion.js file by switching the reqfreehand to false.

2025-01-25 00:57 UTC, DragonSlayer62 commented on source/Changelog.txt
> +	Added Required Free Hand (js potion).
okay

2025-01-25 20:11 UTC, Xoduz approved these changes

2025-01-25 20:32 UTC, merged