Added ML Quivers (dfn clothing)
UOX3DevTeam/UOX3 pull request #301
Opened 2024-08-14 02:22 UTC by DragonSlayer62

2025-01-24 16:36 UTC, Xoduz commented on data/js/item/equip_effects/updatequivercount.js
> +function onAttack( pAttacker, pDefender, hitStatus, hitLoc, damageDealt )
This has a dependency on https://github.com/UOX3DevTeam/UOX3/pull/300, which should be merged first.

2025-01-24 16:44 UTC, Xoduz requested changes

2025-01-24 16:44 UTC, Xoduz commented on data/js/item/archerybutte.js
> +								mItem.Delete();
It seems like this part might be double-dipping on arrow removal. It both iterates through the quiver and reduces arrow count by 1/deletes item if only 1 left, AND it continues on to the part below which consumes an arrow via pUser.UseResource(). Since UseResource() already iterates through all containers in player's pack until it finds what it needs, remove the manual .amount change and .Delete().

2025-01-24 16:44 UTC, Xoduz commented on data/js/item/archerybutte.js
> +								mItem.Delete();
See previous comment about double-dipping on arrow removal. Same applies here.

2025-01-24 16:44 UTC, Xoduz commented on data/dfndata/items/gear/clothing/clothing.dfn
> +}
Add origin=ml tag please :)

2025-01-25 01:19 UTC, DragonSlayer62 commented on data/js/item/archerybutte.js
> +								mItem.Delete();
Reason i doing it that way because it wasnt looking at the quiver and taking the arrow out it was deleting bolts and arrows and this was causing the quiver to break if i remove that it breaks the quiver with archery buttes I know there is a method to my madness with this i promise.

2025-01-26 04:26 UTC, DragonSlayer62 commented on data/js/item/equip_effects/updatequivercount.js
> +function onAttack( pAttacker, pDefender, hitStatus, hitLoc, damageDealt )
done

2025-01-30 10:03 UTC, Xoduz requested changes

2025-01-30 10:03 UTC, Xoduz commented on data/js/item/archerybutte.js
Yeah, this is a no-go. Too many unnecessary changes, and entire portions of the script have been removed with this rework (splitting arrows in bullseye, turning towards butte, etc). I left comments in discord PM, please continue discussion there to address the issues I raised, thanks.

2025-01-30 17:38 UTC, closed without merging