puzzle chest
UOX3DevTeam/UOX3 pull request #307
Opened 2024-10-10 21:12 UTC by DragonSlayer62

This was osi Puzzle chest for kahldun.

2025-01-24 15:53 UTC, Xoduz approved these changes

2025-01-25 09:15 UTC, Xoduz requested changes
I previously approved this, but after looking at it again, I think it needs a changelog update that explains what was added, and how it can be potentially used. However, if there's no way to actually make use of it right now, we may want to delay merging this until it has some more context.

2025-01-26 04:26 UTC, DragonSlayer62 commented
Added changelog with description what it does

2025-01-26 12:25 UTC, Xoduz requested changes
As part of the onCreateDFN event, these puzzle chests should be hidden as soon as they spawn. Then the detect hidden skill should be updated so it can be used to uncover these. Maybe detecting one should trigger a timer on the chest that will re-hide it if it hasn't been opened in X minutes, to reset the experience for the next player? :)

Also, since we don't have a setup for Khaldun dungeon spawns etc yet, the very least we should do before adding these to UOX3 is include them in the 'add menu as something admins/GMs can find/add and consider spawning elsewhere themselves, so it doesn't just become a "lost" feature that no one knows exists.

2025-01-26 23:42 UTC, DragonSlayer62 commented
I added the chest to the addmenu.

2025-01-28 02:53 UTC, DragonSlayer62 commented
After looking on way back machine this chest was never hidden that had to be a update they added since then because only current uoguide says there hidden.

2025-01-28 07:44 UTC, Xoduz approved these changes

2025-01-28 07:44 UTC, merged