CheckInstaLog  Added
UOX3DevTeam/UOX3 pull request #310
Opened 2024-10-15 00:54 UTC by DragonSlayer62

Added the CheckInstaLog function to check if a specific location is within an instant logout zone (SEFunctions.cpp).

2025-01-24 15:43 UTC, Xoduz requested changes

2025-01-24 15:43 UTC, Xoduz commented on docs/jsdocs.html
Same comment as in another PR - please make sure only the relevant changes to the document is submitted (with tabs, not spaces ;), and not the entire file full of changes (tabs to spaces, in this case).

2025-01-28 03:29 UTC, DragonSlayer62 commented
Fixed Doc

2025-01-28 08:33 UTC, Xoduz approved these changes

2025-01-28 08:38 UTC, merged