CheckTimeSinceLastCombat
UOX3DevTeam/UOX3 pull request #311
Opened 2024-10-15 03:23 UTC by DragonSlayer62

Added CheckTimeSinceLastCombat in (SEFunctions.cpp).

2025-01-24 15:41 UTC, Xoduz requested changes

2025-01-24 15:41 UTC, Xoduz commented on docs/jsdocs.html
> +<div class="spoilerWrapper">
Where's the precious tabs at? :D

2025-01-24 15:41 UTC, Xoduz commented on source/Changelog.txt
> +    	Added CheckTimeSinceLastCombat in (SEFunctions.cpp).
Please describe the use case for this. Added this, so you can do what?

2025-01-24 15:41 UTC, Xoduz commented on source/combat.cpp
> +    cTarget->SetLastCombatTime(now);
Tabs, not spaces ;)

2025-01-24 15:41 UTC, Xoduz commented on source/combat.cpp
> +
Tabs, not spaces ;)

2025-01-26 12:57 UTC, Xoduz requested changes
Just noticed this is listed in JS docs under "Miscellaneous" section, when it should be under the "Combat" section :)

2025-01-28 03:25 UTC, DragonSlayer62 commented
Fixed

2025-01-29 22:48 UTC, merged