Added SetRandomColor
UOX3DevTeam/UOX3 pull request #312
Opened 2024-10-20 22:36 UTC by DragonSlayer62

Applies a random color from specified colorlist to character or item

2025-01-24 15:25 UTC, Xoduz requested changes

2025-01-24 15:25 UTC, Xoduz commented on docs/jsdocs.html
This seems like a pretty drastic change just to add something new to the file. Looks like all tabs have been converted to spaces in the file, which is understood as an update of every single line in the entire file. Please address :)

2025-01-26 16:25 UTC, Xoduz commented on docs/jsdocs.html
👆

2025-01-28 03:16 UTC, DragonSlayer62 commented
Fixed Doc

2025-01-28 08:57 UTC, Xoduz approved these changes

2025-01-28 09:11 UTC, merged