Karma Locking
UOX3DevTeam/UOX3 pull request #315
Opened 2024-12-08 20:56 UTC by DragonSlayer62

Added Karma Locking LBR Feature.

2025-01-24 15:18 UTC, Xoduz requested changes

2025-01-24 15:18 UTC, Xoduz commented on source/Changelog.txt
> +	Added Karma Locking LBR Feature.
Specify where you added this, please. Is it an UOX.INI setting?

2025-01-24 15:18 UTC, Xoduz commented on source/npcs.cpp
> +			mSock->SysMessage( 5751 ); // Karma is locked.  A mantra spoken at a shrine will unlock it again.
I see a sysmessage that says to speak a mantra at a shrine to unlock, but I don't see any speech triggers in the shrine script. Something to rectify? Patch notes (from Publish 10, in Third Dawn expansion) said the following:

> Players wishing to remove their karma lock may visit the virtue shrines and speak the following words of power for that shrine:
Compassion – mu
Honesty – ahm
Honor – summ
Humility – lum
Justice – beh
Sacrifice – cah
Spirituality – om
Valor – ra

Likewise, for locking karma through speech:
> If a player with positive karma chooses to lock their karma from raising any higher, they may go to the Chaos Shrine and speak the word “bal”. Doing so will lock their karma, and they will receive the message “You once again control your destiny”.

2025-01-25 01:35 UTC, DragonSlayer62 commented on source/npcs.cpp
> +			mSock->SysMessage( 5751 ); // Karma is locked.  A mantra spoken at a shrine will unlock it again.
this all in the shrine script that is next pr

2025-01-28 09:20 UTC, Xoduz approved these changes

2025-01-28 09:28 UTC, merged